name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore packages, build and test
      run: dotnet test --verbosity normal

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build package
      run: dotnet pack --verbosity normal -c Release -o ./output
    - name: Publish
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: dotnet nuget push ./output/Duffel.ApiClient.*.nupkg -k${{secrets.NUGET_API_KEY}}

